line-length = 90
target-version = "py312"
indent-width = 4

[format]
docstring-code-format = true
preview = true

[lint]
select = ["E", "F", "N", "UP", "ASYNC", "S", "BLE", "B", "A", "C4", "DTZ", "EXE",
        "PIE", "SLF", "SIM", "PL", "PERF", "FURB", "RUF", "FIX", "ISC", "PGH", "ARG",
        "FBT", "TRY", "COM818", "C90", "NPY", "PD", "TC", "YTT", "W291", "W505", "W605"]
ignore = [
	"E741", # ambiguous-variable-name
	"FURB101", # read-whole-file
	"FURB103", # write-whole-file
	"PLR1714", # repeated-equality-comparison
	"PLR2004", # magic-value-comparison
	"PLR6301", # no-self-use
	"RUF005", # collection-literal-concatenation
	"RUF012", # mutable-class-default
	"S101", # assert
	"S304", # suspicious-insecure-cipher-usage
	"S305", # suspicious-insecure-cipher-mode-usage
	"S311", # suspicious-non-cryptographic-random-usage
	"S403", # suspicious-pickle-import
	"S404", # suspicious-subprocess-import
	"S413", # suspicious-pycrypto-import
	"S603", # subprocess-without-shell-equals-true
	"SIM108", # if-else-block-instead-of-if-exp
	"TRY003", # raise-vanilla-args
	"UP015", # redundant-open-modes
	"E111", # indentation-with-invalid-multiple
	"S602", # subprocess-popen-with-shell-equals-true
	"S607", # start-process-with-partial-path
	"UP022", # replace-stdout-stderr
	"PD901", # pandas-df-variable-name
	"TC006", # runtime-cast-value
	"TC007", # unquoted-type-alias
	"TC008", # quoted-type-alias
]
preview = true

[lint.pycodestyle]
max-line-length = 100
