name: ectf_build_server
services:
    ectf_build_server:
        container_name: ectf_build_server
        build:
            dockerfile: ./Dockerfile
            context: .
        ports:
            - "8888:8888"
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - decoder:/root/mounts/decoder
            - build_out:/root/mounts/build_out
            - secrets:/root/mounts/secrets
            - ../scrape-bot/temp:/root/mounts/targets
            - ../scrape-bot/scripts:/root/mounts/scripts
volumes:
    decoder:
    build_out:
    secrets: