services:
    ectf_build:
        container_name: ectf_build_server
        build:
            dockerfile: ./Dockerfile
            context: .
        ports:
            - "8888:8888"
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - 2025-eCTF-design:/root/src/2025-eCTF-design
            - build_out:/root/src/build_out
            - secrets:/root/src/secrets

    ssh-server:
        image: linuxserver/openssh-server
        environment:
            - PUBLIC_KEY_FILE=./id_ed25519.pub
        volumes:
            - config:/config
        ports:
            - 22:2222
volumes:
    config:
    2025-eCTF-design:
    build_out:
    secrets: